"""The demo world, exported from the frontend's ``src/data/seed.ts``.

``fixtures/seed.json`` is generated by ``scripts/export-seed.mjs``; do not edit
it by hand. Slot and review times are hour offsets from local midnight on the
day the world is built, so the demo never shows stale dates, the same trick the
frontend plays with ``at(day, hour)``.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from functools import cache
from importlib import resources
from zoneinfo import ZoneInfo

from pydantic import TypeAdapter

from .models import District, Listing, Owner, Review, Slot, World
from .timeutil import HOUR_MS, iso_from_ms

_listings = TypeAdapter(list[Listing])


def _path():
    return resources.files(__package__).joinpath("fixtures/seed.json")


@cache
def raw() -> dict:
    return json.loads(_path().read_text(encoding="utf-8"))


@cache
def fingerprint() -> str:
    """Identifies this edition of the seed. The catalog stores it next to the
    world it loaded, so a database seeded from an older ``seed.ts`` is
    recognised and rebuilt rather than served with categories that no longer
    exist."""
    return hashlib.sha256(_path().read_bytes()).hexdigest()[:16]


def me() -> str:
    return raw()["me"]


def home_district() -> str:
    return raw()["homeDistrict"]


def midnight_ms(tz: str, at: datetime | None = None) -> int:
    zone = ZoneInfo(tz)
    now = (at or datetime.now(zone)).astimezone(zone)
    midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    return int(midnight.timestamp() * 1000)


def build_slots(tz: str = "Europe/Berlin", at: datetime | None = None) -> list[Slot]:
    base = midnight_ms(tz, at)
    return [
        Slot(
            id=s["id"],
            listing_id=s["listingId"],
            start=iso_from_ms(base + int(s["startHour"] * HOUR_MS)),
            end=iso_from_ms(base + int(s["endHour"] * HOUR_MS)),
            hours_usable=s["hoursUsable"],
        )
        for s in raw()["slots"]
    ]


def build_reviews(tz: str = "Europe/Berlin", at: datetime | None = None) -> list[Review]:
    """Seeded reviews are dated relative to today, like the windows, so a review
    "three weeks ago" stays three weeks ago however long the demo runs."""
    base = midnight_ms(tz, at)
    return [
        Review.model_validate({**r, "at": iso_from_ms(base + int(r["atHour"] * HOUR_MS))})
        for r in raw().get("reviews", [])
    ]


def build_world(tz: str = "Europe/Berlin", at: datetime | None = None) -> World:
    r = raw()
    return World(
        owners=[Owner.model_validate(o) for o in r["owners"]],
        listings=_listings.validate_python(r["listings"]),
        slots=build_slots(tz, at),
        districts={d["name"]: District.model_validate(d) for d in r["districts"]},
        reviews=build_reviews(tz, at),
    )
